print(1 < 2)
print(2 < 1)
print(3 == 3)
print(3 != 3)
print(4 <= 4)
print(5 >= 6)
print(True and False)
print(True or False)
print(not True)
print(1 and 2)
print(0 or 7)
print(1 and 0 or 3)
print(not 0)
print(True + True)
print(1 + 2 < 2 * 2)
