print("hello world")
print('single quotes')
print("it's fine")
print('say "hi"')
print("")
print("tab:\there")
print("nl:\nnext")
print("mix" + "ed" + "up")
print("ab" "cd")
s = "abc"
t = s + "de"
print(t)
print(t == "abcde")
print(t == "abcdf")
print(t != "abcde")
print("a" == "a", "a" == "b")
print("" == "", 1 == "1", "1" == 1)
print(t != "abcde", "x" != "x")
print(t == "abc" + "de")
print(len("hello"))
print(len(s), len(""), len("a b c"))
u = s + s
print(len(u) + len(t))
print(not "")
print(not "x")
print(True and "yes")
print("" or 7)
print(s[0], s[1], s[2])
print("hello"[1])
print(t[0:2], t[1:4], t[2:2])
print(t[:3], t[:0])
print(t[2:], t[5:])
print(t[:])
print(t[3:1], t[2:10], t[10:20])
print(t[True], t[False])
print((s + "fgh")[4:6])
print((s + "fgh")[5])
