"""P12 fixtures: async def / for / with, await, async comprehensions. Oracle-validated like fixtures.py, which imports these."""
# Accepted by the pinned ast.parse; the first were `Unsupported` examples until P12.
ASYNC_STATEMENTS = [
    # The `stmt_async.bend` wire source.
    "@d\nasync def f(a):\n    async with a as b, c:\n        async for x in await b: y = [await z async for z in x if z]\n        else: return await y ** 2\n",
    "class A:\n    async def f(self): pass\n", "@d\nclass A:\n    def f(self): await x\n", "async def f(): pass", "@d\nasync def f(): pass", "async for x in y: pass", "async with a: pass",
    "def f(): await x", "def f(a: int): x: int = await a", "a[await b:]", "f\"{await x}\"", "[x async for x in y]", "(x async for x in y)", "{x async for x in y}", "{a: b async for a in c}",
    "f(x async for x in y)", "[x for x in y async for z in w]", "[await x for x in y]", "[x for x in await y]", "x: await z", "x: int = await z", "x: [y async for y in z]",
    "x: int = [await y for y in z]", "class A:\n    x: int = 1\n    async def f(self): pass\n", "yield await x", "yield from await x", "async def f(): yield",
    "async def f():\n    async for x in y: yield x\n", "def f():\n    yield\n    await x\n", "[(yield) async for x in y]", "await x", "x = await y", "await x ** 2", "-await x", "await (await x)",
    "await x.y(z)[0]", "await x if y else z", "{x: y async for x in y if await z}", "[x async for x in y for z in w async for q in r]", "async def f():\n    async for x in y: pass\n    else: pass\n",
    "async with a as b, c: pass", "async with (a as b, c): pass", "async with (a, b): pass", "async for x, in y: pass", "async for x in *a, b: pass", "await x, y", "x: int = await y", "x += await y",
    "(await x).y = 1", "with await x as y: pass", "return await x", "raise await x from await y", "assert await x, await y", "f(await x, k=await y, *await z, **await w)", "a[await x:await y]",
    "await x[1:2]", "not await x", "a + await b * c", "await a @ b", "2 ** await x", "await x ** await y", "await f'{await x}'", "f'{await x}'", "f'{await x!r:>{await y}}'", "await 1", "await 'a' 'b'",
    "await (yield)", "await [x]", "await {}", "await ...", "await None", "await(x)", "await[x]", "x if await y else await z", "lambda: await x", "await x < await y", "await x and await y",
    "async def f(x=await y) -> await z: pass", "class A(await x): pass", "await x; await y", "if await x: pass\nelif await y: pass", "while await x: pass", "[x async for x in await y if await z]",
    "async for x in y:\n    pass\nelse:\n    pass\n", "async def f():\n    return [x async for x in y]\n", "async with a:\n    pass\n", "async with a as (b, c), d as e.f:\n    pass;\n",
    "async def f(): x;", "await x,", "(await x,)", "await\\\nx", "async \\\n def f(): pass", "async  def  f (a, /, b: int = 1, *c, d, **e) -> T: return await a", "print(await x)", "await x.y",
    "- - await x", "await x()()", "(await x).y: int",
    "async def f():\n    async with a as b, c as d:\n        async for x in y:\n            await x\n        else:\n            await y\n    return [await z async for z in w if await z]\n",
    "class A:\n    @staticmethod\n    async def f(self, *a, **k) -> None:\n        '''doc'''\n        x = await self.g(*a, **k)\n        return x\n", "@a\n@b(c)\nasync def f(): pass\n",
    "async def f(): pass;", "async for x in y: pass;", "async with a: pass;", "async for x in y: pass\nelse: pass;", "if a:\n    async def f(): pass\nelse:\n    async with a: pass\n",
    "async with (a, b) as c: pass", "async with (a): pass", "async with (a) as b, (c): pass", "async with (yield): pass", "async with (\n    a as b,\n    c as d,\n): pass",
    "async for (x, y) in z: pass", "async for x.y in z: pass", "async for x[0], *y in z: pass", "async for x in y, z: pass", "async for x in (yield): pass", "{x: y async for x, y in z}",
    "((x, y) async for x, y in z async for a in b if c if d)", "[x async for x in y if await z async for w in await v]", "[[y async for y in x] async for x in z]", "(await x async for x in y)",
    "((yield) async for x in y)", "await x.y.z", "await x[0][1]", "await x(y)(z).w", "await (x)", "await (x).y", "(await x)(y)", "(await x)[0]", "(await x) ** 2", "await x ** -y",
    "await x ** await y ** await z", "-await x ** 2", "~await x", "+await x", "await x * await y + await z", "await x @ await y", "await x if await y else await z", "await x or await y and not await z",
    "await x < await y <= await z", "await x is not await y", "await x not in await y", "await x, await y", "*await x, y", "x = *await y,", "x = await y, await z", "x = y = await z",
    "x: await y = await z", "x[await y] = await z", "x.y[await z].w = 1", "(await x).y += 1", "(await x)[0]: int = 1", "del (await x).y", "del (await x)[0], z", "for x in await y: pass",
    "for x in await y, await z: pass", "for (await x).y in z: pass", "with await x, await y as z: pass", "with (await x as y, await z): pass", "with (await x): pass", "return await x, await y",
    "return (await x)", "raise await x", "assert await x", "try: pass\nexcept await E: pass", "try: pass\nexcept await x as e: pass", "await[0]", "await ()", "await (x, y)", "await (x for x in y)",
    "await [x for x in y]", "await {x: y}", "await {x}", "await f'{x}'", "await 'a'", "await 1.5j", "await True", "await (x if y else z)", "await (lambda: x)", "await (not x)", "await (-x)",
    "await (yield x)", "await (yield from x)", "f(await x)", "f(await x, await y)", "f(k=await x)", "f(*await x)", "f(**await x)", "f(await x for x in y)", "f(x)(await y)", "x[await y]",
    "x[await y:await z:await w]", "x[await y, await z]", "x[::await y]", "[await x]", "[await x, await y]", "[*await x]", "{await x}", "{await x: await y}", "{**await x}",
    "{await x: await y for x in await z if await w}", "lambda x=await y: x", "def f(x=await y): pass", "def f(x: await y): pass", "def f() -> await y: pass", "@await x\ndef f(): pass",
    "@(await x)\ndef f(): pass", "class A(await x, k=await y): pass", "if await x: pass", "while await x: await y", "f'{await x!r}'", "f'{await x:>{await y}}'", "f'{await x=}'", "f'{ await x }'",
    "f'{x async for x in y}'", "f'{[x async for x in y]}'", "yield await x, await y", "x = yield await y", "await x\\\n.y", "(await\n x)", "(await x\n .y)", "[x\n async\n for x in y]",
    "async \\\ndef f(): pass", "async def f():\n\tawait x\n\tasync with y: pass\n", "async def f(): await x; await y", "async def f(): return await x",
    "async def f():\n    async def g():\n        async def h(): await x\n", "async def f():\n    try:\n        await x\n    except E:\n        await y\n    finally:\n        await z\n",
    "async def f(x, /, y, *, z): pass", "async def f(*a: int, **k: str) -> 'T': pass", "async def f(): yield await x",
]
# Both words are keywords in 3.11: no `async = 1`, no `await` name; `await` takes a primary.
ASYNC_INVALID = [
    "async = 1", "async()", "async.attr", "await = 1", "await -x", "await await x", "await not x", "await lambda: 1", "@d\nasync for x in y: pass", "async class A: pass", "async if x: pass",
    "async\ndef f(): pass", "async x", "x = async", "def await(): pass", "def async(): pass", "f(await=1)", "x.await", "x.async", "import async", "from async import x", "lambda await: 1", "await",
    "await *x", "await x = 1", "(await x) = 1", "del await x", "del (await x)", "for await x in y: pass", "global async", "[x async x in y]", "[async for x in y]", "await -1", "await ~x", "await +x",
    "x = await", "(await)", "f(await)", "await yield", "await: int", "await x: int", "(await x): int", "@a\nasync\ndef f(): pass", "@a\nasync class A: pass", "@a\nasync with x: pass",
    "async for x in yield: pass", "async for x in y", "async for x y: pass", "async with: pass", "async with a as: pass", "async def: pass", "async def f: pass", "async def f()",
    "async def f() -> : pass", "async lambda: 1", "async import a", "async try: pass", "async while x: pass", "async pass", "async", "async async def f(): pass", "async await x",
    "x = async def f(): pass", "(async for x in y)", "[x async]", "[x async for]", "[x async for x]", "[x async for x in]", "[x async in y]", "[x async for x in y async]", "[x for x in y async]",
    "{x: y async for}", "f(x async for x in y, 1)", "f(1, x async for x in y)", "f(*x async for x in y)", "(x, y async for x in y)", "(yield async for x in y)", "[x async for x in a if b else c]",
    "[x async for x in lambda: y]", "import await", "from a import await", "from a import b as await", "global await", "nonlocal await", "class await: pass", "class A(await=1): pass",
    "def f(await): pass", "def f(*, async): pass", "lambda async: 1", "lambda: async", "try: pass\nexcept E as await: pass", "with a as await: pass", "with a as async: pass", "for async in x: pass",
    "for x in async: pass", "await.x", "await lambda: x", "await **x", "await;", "await += 1", "await x += 1", "(await x) += 1", "[await x] = 1", "await x, y = 1", "with a as await x: pass",
    "with a as (await x): pass", "f(await=x)", "f(await,)", "f'{await}'", "f'{await -x}'", "f'{async}'",
]
