"""P14 fixtures: `match` statements (PEP 634), `except*` (TryStar), the soft keywords, and the negatives of the retired refuse-first policy (a compound statement or `@` in a simple position). Oracle-validated like fixtures.py, which imports these."""
# Accepted by the pinned ast.parse. The first is the `stmt_match.bend` wire source; the soft-keyword lines are simple statements.
MATCH_STATEMENTS = [
   
    'def f(s):\n    match s.x, *t:\n        case [0 | -1 as a, *_] | {\'k\': None, **r} if (n := a): return C(a.b, (p, \'q\' "r"), y=1+2j)\n        case D.E(True, z=[]) | () as w:\n            match = case = w\n',
    'match s:\n    case 1: pass\n', 'match s:\n    case -1: pass\n', 'match s:\n    case - 1: pass\n', 'match s:\n    case 1j: pass\n', 'match s:\n    case -1j: pass\n',
    'match s:\n    case 1+2j: pass\n', 'match s:\n    case 1-2j: pass\n', 'match s:\n    case -1+2j: pass\n', 'match s:\n    case -1-2j: pass\n', 'match s:\n    case 1.5+2j: pass\n',
    'match s:\n    case 0x1+2j: pass\n', 'match s:\n    case -0: pass\n', 'match s:\n    case "a": pass\n', 'match s:\n    case "a" "b": pass\n', 'match s:\n    case b"a": pass\n',
    'match s:\n    case f"a": pass\n', 'match s:\n    case f"{x}": pass\n', 'match s:\n    case "a" f"{x}": pass\n', 'match s:\n    case None: pass\n', 'match s:\n    case True: pass\n',
    'match s:\n    case False: pass\n', 'match s:\n    case x: pass\n', 'match s:\n    case _: pass\n', 'match s:\n    case __: pass\n', 'match s:\n    case __x: pass\n',
    'match s:\n    case _x: pass\n', 'match s:\n    case x.y: pass\n', 'match s:\n    case x.y.z: pass\n', 'match s:\n    case x._: pass\n', 'match s:\n    case x.y(): pass\n',
    'match s:\n    case x(): pass\n', 'match s:\n    case x(1): pass\n', 'match s:\n    case x(a,): pass\n', 'match s:\n    case x(a=1): pass\n', 'match s:\n    case x(a=1,): pass\n',
    'match s:\n    case x(1, a=1): pass\n', 'match s:\n    case x(a=1, a=2): pass\n', 'match s:\n    case x(_=1): pass\n', 'match s:\n    case x.y(a, b=c): pass\n', 'match s:\n    case (x): pass\n',
    'match s:\n    case (x,): pass\n', 'match s:\n    case (): pass\n', 'match s:\n    case (x, y): pass\n', 'match s:\n    case (x, y,): pass\n', 'match s:\n    case (*x,): pass\n',
    'match s:\n    case []: pass\n', 'match s:\n    case [x]: pass\n', 'match s:\n    case [x,]: pass\n', 'match s:\n    case [*x]: pass\n', 'match s:\n    case [*_]: pass\n',
    'match s:\n    case [*x, *y]: pass\n', 'match s:\n    case [x, *y, z]: pass\n', 'match s:\n    case [* x]: pass\n', 'match s:\n    case *x,: pass\n', 'match s:\n    case *x, y: pass\n',
    'match s:\n    case x, y: pass\n', 'match s:\n    case x,: pass\n', 'match s:\n    case x, y,: pass\n', 'match s:\n    case x, *_: pass\n', 'match s:\n    case x, *y, z: pass\n',
    'match s:\n    case {}: pass\n', 'match s:\n    case {**x}: pass\n', 'match s:\n    case {**x,}: pass\n', 'match s:\n    case {"a": 1}: pass\n', 'match s:\n    case {"a": 1,}: pass\n',
    'match s:\n    case {"a": 1, **r}: pass\n', 'match s:\n    case {"a": 1, **r,}: pass\n', 'match s:\n    case {a.b: 1}: pass\n',
    'match s:\n    case {1: x, -2: y, 1+2j: z, None: w, True: v}: pass\n', 'match s:\n    case {f"a": 1}: pass\n', 'match s:\n    case {"a": 1, "a": 2}: pass\n',
    'match s:\n    case {1: x as y}: pass\n', 'match s:\n    case x as y: pass\n', 'match s:\n    case (x as y) as z: pass\n', 'match s:\n    case _ as y: pass\n',
    'match s:\n    case (x) as y: pass\n', 'match s:\n    case ((x)): pass\n', 'match s:\n    case [(x), y]: pass\n', 'match s:\n    case x as y, z: pass\n', 'match s:\n    case x if y: pass\n',
    'match s:\n    case - 1j: pass\n', 'match s:\n    case 1 + 2J: pass\n', 'match s:\n    case 1_0: pass\n', 'match s:\n    case 0o7: pass\n', 'match s:\n    case 1e3+2j: pass\n',
    'match s:\n    case 1e3j: pass\n', 'match s:\n    case C(x, (y, z), [a, *b], {"k": v, **r}): pass\n', 'match s:\n    case a.b.c(d.e, f=g.h): pass\n', 'match s:\n    case case: pass\n',
    'match s:\n    case match: pass\n', 'match s:\n    case case(match): pass\n', 'match s:\n    case print: pass\n', 'match s:\n    case type: pass\n', 'match s:\n    case x | y: pass\n',
    'match s:\n    case 1 | 2 | 3: pass\n', 'match s:\n    case x | y as z: pass\n', 'match s:\n    case (x | y) as z: pass\n', 'match s:\n    case x | (y as z): pass\n',
    'match s:\n    case (1) | 2: pass\n', 'match s:\n    case 1 | (2): pass\n', 'match s:\n    case {"a": x | y}: pass\n', 'match s:\n    case [x | y, *z]: pass\n',
    'match s:\n    case C(a | b, k=c | d): pass\n', "match s:\n    case a.b | c.d | None | -1 | 'a': pass\n", 'match s:\n    case {_.a: 1}: pass\n', 'match s:\n    case x if y := 1: pass\n',
    'match s:\n    case x if (yield): pass\n', 'match s:\n    case x if lambda: 1: pass\n', 'match s:\n    case x:\n        pass\n    case y:\n        pass\n',
    'match s:\n    case x: pass\n\n    # c\n\n    case y: pass\n', 'match s:\n    case x: a; b\n', 'match s:\n    case x:\n        match t:\n            case y: pass\n    case z: pass\n',
    'case = 2\ncase(x)\ncase.x\n', 'match = 1\nmatch(x)\nmatch.x\nmatch[x]\nmatch, x = 1, 2\nmatch: int = 1\nmatch += 1\nmatch * x\nmatch -x\nmatch [x]: int\nmatch (x).y: int = 3\nmatch\n',
    'match [x]: int = 1\n', 'match x:\n    case(y): pass\n', 'match x:\n    case (y): pass\n', 'match x:\n    case [y]: pass\n', 'match x:\n    case {}: pass\n',
    'match x:\n  case 1:\n    pass\n  case 2: pass\n', 'match(x):\n    case 1: pass\n', 'match[x]:\n    case 1: pass\n', 'match{x}:\n    case 1: pass\n',
    'match x:\n    case 1: pass\nmatch y:\n    case 2: pass\n', 'match x:\n    case\\\n 1: pass\n', 'match \\\n x:\n    case 1: pass\n', 'match (x,\n y):\n    case (1,\n 2): pass\n',
    'match x: # c\n    # c\n    case 1: pass # c\n', 'async def f():\n    match await x:\n        case 1: await y\n', 'class A:\n    match x:\n        case 1: pass\n', 'match x:\n    case 1: pass;\n',
    'match x:\n    case 1 if a: pass\n    case 2 if b if c else d: pass\n', 'match x,:\n    case 1,: pass\n', 'match x:\n    case 1, if a: pass\n', 'match x:\n    case a.b.c.d: pass\n',
    'match x:\n    case -1.5e3 - 2.5J: pass\n', 'match x:\n    case - 1 + 2j: pass\n', 'match x:\n    case 1 +\\\n 2j: pass\n', 'match x:\n    case (1 +\n 2j): pass\n',
    'match x:\n    case (\n 1 | 2\n ) as y: pass\n', 'match x:\n    case C(\n  a,\n  b=c,\n ): pass\n', "match x:\n    case {\n  'a': 1,\n  **r,\n }: pass\n",
    'match x:\n    case [\n  a,\n  *b,\n ]: pass\n', 'match = lambda: 1\n', 'print(match)\n', 'match x:\n\tcase 1: pass\n', 'match -x:\n    case 1: pass\n', 'match - x\n', 'match *x\n',
    'match not in x\n', 'match in x\n', 'match is x\n', 'match if x else y\n', 'match or x\n', 'match and x\n', 'match; x\n', 'match == x\n', 'match @ x\n', 'match ...:\n    case 1: pass\n',
    'match x:\n    case 1: pass\n    case 2: pass', 'match x:\n    case 1:\n        pass', 'match x := 1:\n    case _: pass\n', 'match *a, b:\n    case _: pass\n', 'match a,:\n    case _: pass\n',
    'match (yield):\n    case _: pass\n', 'match lambda: 1:\n    case _: pass\n', 'match x if y else z:\n    case _: pass\n', 'match await x:\n    case _: pass\n', 'match not x:\n    case _: pass\n',
    'match a, b if c else d:\n    case _: pass\n', 'match x,y,:\n    case _: pass\n', 'match (x):\n    case _: pass\n', 'match [x]:\n    case _: pass\n', 'match {x}:\n    case _: pass\n',
    'match -x:\n    case _: pass\n', 'match x.y:\n    case _: pass\n', 'match match:\n    case _: pass\n', 'match case:\n    case _: pass\n', 'match *a,:\n    case _: pass\n',
    'match x := 1, y := 2:\n    case _: pass\n', 'match "a" "b":\n    case _: pass\n', 'match ...:\n    case _: pass\n', 'match 1:\n    case _: pass\n',
    "match x:\n    case [a, b] if a > b:\n        r = 1\n    case {'k': v, **rest} | C(v, rest=rest):\n        r = 2\n    case str() | bytes() as s:\n        r = 3\n    case _:\n        r = 4\n",
    "def f(x):\n    match x:\n        case 0: return 'zero'\n        case int(n) if n < 0: return 'neg'\n        case [Point(x=0, y=0), *rest]: return rest\n    return None\n",
    "class A:\n    def g(self, c):\n        match c.split():\n            case ['go', d] | ['move', d]:\n                self.go(d)\n            case ['quit']:\n                pass\n",
    'match x:\n    case 1:\n        match y:\n            case 2:\n                match z:\n                    case 3: pass\n            case _: pass\n    case _:\n        pass\nx = 1\n',
    'for a in b:\n    match a:\n        case None: continue\n        case True | False: break\nelse:\n    pass\n', 'try:\n    match x:\n        case E(): raise x\nexcept E:\n    pass\n',
    'with a:\n    match x:\n        case (1, 2) as p, q: pass\n', 'match x:\n    case a.b: pass\n    case a.b(): pass\n    case a.b(c.d): pass\n    case {a.b: c.d}: pass\n',
    "match x:\n    case 'a' 'b' | b'c' | f'd': pass\n", 'match x:\n    case (): pass\n    case (()): pass\n    case ((),): pass\n    case [[]]: pass\n    case [(), []]: pass\n',
    'match x:\n    case ((a)): pass\n    case ((a, b)): pass\n    case ((a) as b): pass\n    case (a | b): pass\n    case ((a | b) as c) | d: pass\n',
    'match x:\n    case [*_]: pass\n    case [*_, a]: pass\n    case (*a,): pass\n    case *a, b: pass\n    case a, *_: pass\n',
    "match x:\n    case {1: _, 'a': _, None: _, True: _, False: _, -1: _, 1+2j: _, a.b: _}: pass\n",
    'match x:\n    case C(): pass\n    case C(_): pass\n    case C(_, a=_): pass\n    case C(a=_,): pass\n    case a.b.C(d, e=f): pass\n',
    'match x:\n    case 0x1F | 0b1 | 0o7 | 1_000 | 1.5 | 1e3 | 2j: pass\n', 'match match:\n    case case: pass\n', 'match case:\n    case match: pass\n', 'match _:\n    case _: pass\n',
    'match x:\n    case match(case=_): pass\n', 'match x:\n    case case.match: pass\n', 'match x:\n    case 1:\n        case = 1\n        match = 2\n',
    'match x:\n    case 1: match = 1\n    case 2: case = 2\n', 'match(x)\nmatch x:\n    case 1: pass\nmatch(x)\n', 'match x:\n    case 1: pass\n\n\n\n',
    'match x:\n    case 1:\n\n        pass\n\n    case 2:\n\n        pass\n', 'match (x := f()):\n    case y if (z := y): pass\n', 'if x := 1:\n    match x:\n        case _: pass\n',
    'match f(a)[b].c:\n    case _: pass\n', 'match [a, b]:\n    case _: pass\n', 'match {a: b}:\n    case _: pass\n', 'match (a, b), c:\n    case _: pass\n',
    'match x if y else z, *w:\n    case _: pass\n', 'match a < b:\n    case _: pass\n', 'match a or b:\n    case _: pass\n', "match f'{a}':\n    case _: pass\n",
    'match [i for i in y]:\n    case _: pass\n', 'match (i for i in y):\n    case _: pass\n', 'match (yield x):\n    case _: pass\n', 'match 1, 2:\n    case 1, 2: pass\n',
    'match x:\n    case a if a: pass\n    case b if b and c: pass\n    case d if [e for e in d]: pass\n    case g if f(g): pass\n', 'match x:\n    case [a, [b, [c, [d]]]]: pass\n',
    "match x:\n    case {'a': {'b': [c, {'d': e}]}}: pass\n", 'match x:\n    case A(B(C(d)), e=F(g=h)): pass\n', 'match x:\n    case a | b | c | d | e: pass\n',
    'match x:\n    case [a | b, c | d] | (e | f): pass\n', 'match x:\n    case [1 as a, 2 as b] as c: pass\n', "match x:\n    case {'a': 1 as b, **c}: pass\n",
    'match x:\n    case C(1 as a, b=2 as c): pass\n', 'match x:\n    case - 1: pass\n    case -  1.0: pass\n', 'match x:\n    case 1 -2j: pass\n    case 1-2j: pass\n    case -1 + 2J: pass\n',
    "match x:\n    case 'a': pass\n    case '''b''': pass\n    case r'c': pass\n    case b'd' b'e': pass\n", "match x:\n    case f'{a}' 'b': pass\n",
    'match x:\n    case [\n        a,  # c\n        b,\n    ]: pass\n', 'match x:\n    case (a\n          | b): pass\n', 'match x:\n    case C(a,\n           b): pass\n',
    "match x:\n    case {'a': 1,\n          'b': 2}: pass\n", 'match x:\n    case 1: pass\n    # tail\n', 'match x:\n    # head\n    case 1: pass\n', 'match x:\n    case 1: return\n',
    'match x:\n    case 1: a = 1; b = 2\n    case 2: del a\n', 'match x:\n    case 1:\n        if a: pass\n        else: pass\n    case 2:\n        while a: pass\n',
    'match x:\n    case 1:\n        def f(): pass\n    case 2:\n        class A: pass\n', 'match x:\n    case 1:\n        @d\n        def f(): pass\n',
    'match x:\n    case 1:\n        async def f(): await y\n', 'lambda: match', 'match.case', 'match[case]', 'match(case)', 'case[match]: int', 'match: case = 1', 'match, case = 1, 2',
    'match = case = 1', 'match += case', 'match -case', 'match +x', 'match *x, y', 'match **x', 'match / x', 'match < x', 'match if case else x', 'match and case', 'match or case',
    'match not in case', 'match is not case', 'match; case', 'match', 'case', '_', 'del match, case', 'for match in case: pass', 'with match as case: pass', 'def match(case): pass',
    'def case(match=1): pass', 'import match.case', 'global match', '[match for match in case]', 'f(match=1, case=2)', 'x.match.case', 'match.match', 'return match', 'assert match, case', 'match (x)',
    'match (x).y', 'match (x)[0]', 'match (x)(y)', 'match (x), y', 'match (x) + 1', 'match (x) if a else b', 'match [x]', 'match [x][0]', 'match [x], y', 'match [x] + [y]', 'match [x] = 1',
    'match [x]: int', 'match (x).y: int', 'match [x][0]: int = 1', 'match (x)\nmatch [y]\n', 'match (x,\n y)', 'if a: match = 1', 'if a: match(x)', 'while a: match -x', 'class A: match = 1',
    'def f(): match', 'for a in b: case(x)', 'if a: case = 1', 'match x:\n    case _: pass\n', 'match x, y:\n    case _: pass\n', 'match (x), y:\n    case _: pass\n',
    'match (x).y[0]:\n    case z: w: int = 1\n', 'match x:\n    case _:\n        y: int = 1\n', 'async def f():\n    match x:\n        case _: await y\n',
    'def f():\n    match x:\n        case _: yield\n', 'match (x := 1):\n    case _: pass\n', 'match x, y := 1:\n    case 1: pass\n', 'match x:\n    case C(a, b=1, _=2): pass\n',
    'match x:\n    case C(_=1, _=2): pass\n', 'match x:\n    case C(_, a=_): pass\n', 'try: pass\nexcept* E: pass', 'try: pass\nexcept * E: pass', 'try: pass\nexcept*E as e: pass',
    'try: pass\nexcept* (A, B) as e: pass\nexcept* C: pass\nelse: pass\nfinally: pass', 'try: pass\nexcept* (x := E): pass', 'try: pass\nexcept* E if a else F: pass',
    'try: pass\nexcept* lambda: 1: pass', 'try:\n    pass\nexcept* E:\n    try: pass\n    except* F: pass\n    try: pass\n    except G: pass\n', 'def f():\n    try: pass\n    except* E: return\n',
    'try: pass\nexcept* E: pass\nelse: pass', 'try: pass\nexcept* E: pass\nfinally: pass', 'try: pass\nexcept* await x: pass', 'try: pass\nexcept* (yield): pass', 'try: pass\nexcept* E as _: pass',
    'try: pass\nexcept*\\\n E: pass', 'try:\n    pass\nexcept* a.b as e:\n    x = 1\n    y = 2\nexcept* f(x)[0]:\n    pass\nfinally:\n    z = 3\n',
    'async def f():\n    try:\n        await x\n    except* E as e:\n        match e:\n            case E(): raise\n', 'try: pass\nexcept* E as match: pass',
]

# SyntaxError in the pinned ast.parse; both lanes must answer Syntax.
MATCH_INVALID = [
    'match s:\n    case +1: pass\n', 'match s:\n    case --1: pass\n', 'match s:\n    case 1j+2j: pass\n', 'match s:\n    case 1+2: pass\n', 'match s:\n    case 1 + -2j: pass\n',
    'match s:\n    case "a" b"b": pass\n', 'match s:\n    case ...: pass\n', 'match s:\n    case _.y: pass\n', 'match s:\n    case _(): pass\n', 'match s:\n    case x(a=1, 2): pass\n',
    'match s:\n    case x(*a): pass\n', 'match s:\n    case x(**a): pass\n', 'match s:\n    case x(a)(b): pass\n', 'match s:\n    case x[0]: pass\n', 'match s:\n    case x.y[0]: pass\n',
    'match s:\n    case x()(): pass\n', 'match s:\n    case (*x): pass\n', 'match s:\n    case [*x.y]: pass\n', 'match s:\n    case [*(x)]: pass\n', 'match s:\n    case *x: pass\n',
    'match s:\n    case {**_}: pass\n', 'match s:\n    case {**r, "a": 1}: pass\n', 'match s:\n    case {a: 1}: pass\n', 'match s:\n    case {"a": *x}: pass\n', 'match s:\n    case {(1): x}: pass\n',
    'match s:\n    case {x.y(): 1}: pass\n', 'match s:\n    case {**a, **b}: pass\n', 'match s:\n    case {**a.b}: pass\n', 'match s:\n    case x as _: pass\n', 'match s:\n    case x as y.z: pass\n',
    'match s:\n    case x as y as z: pass\n', 'match s:\n    case *x as y: pass\n', 'match s:\n    case (*x as y,): pass\n', 'match s:\n    case x: int: pass\n', 'match s:\n    case x = 1: pass\n',
    'match s:\n    case x := 1: pass\n', 'match s:\n    case -x: pass\n', 'match s:\n    case -x.y: pass\n', 'match s:\n    case not x: pass\n', 'match s:\n    case x + 1: pass\n',
    'match s:\n    case x.y + 1: pass\n', 'match s:\n    case 1 if x else 2: pass\n', 'match s:\n    case lambda: 1: pass\n', 'match s:\n    case [x for x in y]: pass\n',
    'match s:\n    case x[1:2]: pass\n', 'match s:\n    case 1 < 2: pass\n', 'match s:\n    case "a" + "b": pass\n', 'match s:\n    case 1 - - 2j: pass\n',
    'match s:\n    case C(x, y=D(z), *, w): pass\n', 'match s:\n    case x as y | z: pass\n', 'match s:\n    case x |: pass\n', 'match s:\n    case | x: pass\n', 'match s:\n    case x | | y: pass\n',
    'match s:\n    case x | *y: pass\n', 'match s:\n    case {_: 1}: pass\n', 'match s:\n    case _._: pass\n', 'match s:\n    case C(_.a): pass\n', 'match s:\n    case x if y, z: pass\n',
    'match s:\n    case x if *y: pass\n', 'match s:\n    case x if: pass\n', 'match s:\n    case x: pass\n    pass\n', 'match s:\n    pass\n', 'match s:\n    case x: pass\n    else: pass\n',
    'match s:\n    case x: pass\nelse: pass\n', 'match s: case x: pass\n', 'match s:\ncase x: pass\n', 'match s:\n    case: pass\n', 'match s:\n    case x\n', 'match s:\n    case x: \n',
    'if a: match x:\n    case _: pass\n', 'case x: pass\n', 'match (x): int\n', 'match x:\n    case = 1\n', 'match x:\n    case 1: pass\n  case 2: pass\n', 'match lambda: 1\n',
    'match x:\n    case 1:\n        pass\n    case _:\n        pass\nelse:\n    pass\n', 'match x:\n    case 1: pass\n    case 2: pass\n    x = 1\n', 'match x:\n    x = 1\n    case 1: pass\n',
    'match * x, y = 1\n', 'match (x) = 1\n', 'match x, y = 1\n', 'match 1\n', "match 'a'\n", 'match x\n', 'match.x:\n    case 1: pass\n', 'match .x:\n    case 1: pass\n',
    'match *a:\n    case _: pass\n', 'match yield:\n    case _: pass\n', 'match x: pass\n    case _: pass\n', 'match:\n    case _: pass\n', 'match = 1\n    case _: pass\n',
    'match(x)\n    case _: pass\n', 'match[x]\n    case _: pass\n', 'match **a:\n    case _: pass\n', 'match x for x in y:\n    case _: pass\n', 'match ~x', 'match {x}', 'match {x: y}',
    'match (x) = 1', 'match (x): int = 1', 'match x:\n    case 1: pass\n   case 2: pass\n', 'match x:\ncase 1: pass\n', 'match x:\n    case 1:\n    pass\n', 'match x:\n    case 1 pass\n',
    'match x:\n    case 1:: pass\n', 'match x:\n    case 1 if: pass\n', 'match x:\n    case if a: pass\n', 'match x:\n    case 1 if a if b: pass\n', 'match x:\n    case 1 as: pass\n',
    'match x:\n    case as y: pass\n', 'match x:\n    case 1 as 2: pass\n', 'match x:\n    case 1 as None: pass\n', 'match x:\n    case 1 as (y): pass\n', 'match x:\n    case None as _: pass\n',
    'match x:\n    case [a, b: pass\n', 'match x:\n    case a, b]: pass\n', 'match x:\n    case (a, b]: pass\n', 'match x:\n    case [a b]: pass\n', 'match x:\n    case [a,, b]: pass\n',
    'match x:\n    case [,]: pass\n', 'match x:\n    case (,): pass\n', 'match x:\n    case ,: pass\n', 'match x:\n    case a,,: pass\n', 'match x:\n    case {,}: pass\n',
    "match x:\n    case {'a'}: pass\n", "match x:\n    case {'a':}: pass\n", 'match x:\n    case {: 1}: pass\n', "match x:\n    case {'a': 1 'b': 2}: pass\n", 'match x:\n    case {**a, **b}: pass\n',
    "match x:\n    case {**a, 'b': 1}: pass\n", 'match x:\n    case {**}: pass\n', 'match x:\n    case {**1}: pass\n', 'match x:\n    case {**a: 1}: pass\n', 'match x:\n    case {*a}: pass\n',
    'match x:\n    case {[1]: a}: pass\n', 'match x:\n    case {-a.b: 1}: pass\n', 'match x:\n    case {a.b(): 1}: pass\n', 'match x:\n    case {1 | 2: a}: pass\n',
    'match x:\n    case {f: 1}: pass\n', 'match x:\n    case C(: pass\n', 'match x:\n    case C(a b): pass\n', 'match x:\n    case C(,): pass\n', 'match x:\n    case C(a=): pass\n',
    'match x:\n    case C(=a): pass\n', 'match x:\n    case C(a=1, b): pass\n', 'match x:\n    case C(a.b=1): pass\n', 'match x:\n    case C(1=a): pass\n', 'match x:\n    case C(*a): pass\n',
    'match x:\n    case C(**a): pass\n', 'match x:\n    case C(a, *b): pass\n', 'match x:\n    case C(a=*b): pass\n', 'match x:\n    case C()(): pass\n', 'match x:\n    case C().a: pass\n',
    'match x:\n    case C()[0]: pass\n', 'match x:\n    case 1(): pass\n', "match x:\n    case 'a'(): pass\n", 'match x:\n    case None(): pass\n', 'match x:\n    case (a)(): pass\n',
    'match x:\n    case (a).b: pass\n', 'match x:\n    case a.(b): pass\n', 'match x:\n    case a.1: pass\n', 'match x:\n    case a.: pass\n', 'match x:\n    case .a: pass\n',
    'match x:\n    case a..b: pass\n', 'match x:\n    case a.None: pass\n', 'match x:\n    case None.a: pass\n', 'match x:\n    case True(): pass\n', 'match x:\n    case -None: pass\n',
    'match x:\n    case -True: pass\n', "match x:\n    case -'a': pass\n", 'match x:\n    case -a: pass\n', 'match x:\n    case -(1): pass\n', 'match x:\n    case (-1)+2j: pass\n',
    'match x:\n    case 1+(2j): pass\n', 'match x:\n    case 1+2j+3j: pass\n', 'match x:\n    case 1+j: pass\n', 'match x:\n    case 1+: pass\n', 'match x:\n    case 1*2j: pass\n',
    'match x:\n    case 1**2: pass\n', 'match x:\n    case 2j+1: pass\n', 'match x:\n    case 2j-1j: pass\n', 'match x:\n    case a+2j: pass\n', 'match x:\n    case a.b+2j: pass\n',
    "match x:\n    case 'a'+2j: pass\n", "match x:\n    case 1+'a': pass\n", 'match x:\n    case 1+None: pass\n', 'match x:\n    case ~1: pass\n', 'match x:\n    case not 1: pass\n',
    'match x:\n    case 1 or 2: pass\n', 'match x:\n    case 1 and 2: pass\n', 'match x:\n    case 1 | : pass\n', 'match x:\n    case | 1: pass\n', 'match x:\n    case 1 || 2: pass\n',
    'match x:\n    case 1 | *a: pass\n', 'match x:\n    case *a | b: pass\n', 'match x:\n    case * : pass\n', 'match x:\n    case *1: pass\n', 'match x:\n    case *(a): pass\n',
    'match x:\n    case **a: pass\n', 'match x:\n    case *a.b,: pass\n', 'match x:\n    case *None,: pass\n', 'match x:\n    case [*a as b]: pass\n', 'match x:\n    case (*a): pass\n',
    'match x:\n    case (*a) as b: pass\n', 'match x:\n    case a as b as c: pass\n', 'match x:\n    case a as b | c: pass\n', 'match x:\n    case a as b.c: pass\n',
    'match x:\n    case a as b(): pass\n', 'match x:\n    case a = 1: pass\n', 'match x:\n    case a := 1: pass\n', 'match x:\n    case a: int: pass\n', 'match x:\n    case a for a in b: pass\n',
    'match x:\n    case [a for a in b]: pass\n', 'match x:\n    case a[0]: pass\n', 'match x:\n    case a[:]: pass\n', 'match x:\n    case a if b, c: pass\n', 'match x:\n    case a if *b: pass\n',
    'match x:\n    case a if b = c: pass\n', 'match x:\n    case a if yield: pass\n', 'match x:\n    case lambda: pass\n', 'match x:\n    case if: pass\n', 'match x:\n    case def: pass\n',
    'match x:\n    case in: pass\n', 'match x:\n    case await a: pass\n', 'match x:\n    case yield: pass\n', 'match x:\n    case ...: pass\n', 'match x:\n    case 1 2: pass\n',
    'match x:\n    case a b: pass\n', "match x:\n    case 'a' b: pass\n", "match x:\n    case 'a' 1: pass\n", "match x:\n    case b'a' 'b': pass\n", 'match x:\n    case: pass\n',
    'match x:\n    case\n', 'match x:\n    case 1\n', 'match x:\n    case 1:\n', 'match x:\n    case 1: pass\n    else: pass\n', 'match x:\n    case 1: pass\n    elif a: pass\n',
    'match x:\n    case 1: pass\n    pass\n', 'match x:\n    pass\n    case 1: pass\n', 'match x:\n    pass\n', 'match x:\n    case 1: pass\n    x\n', 'match x:\n    case 1: pass\n    case\n',
    'match x:\n    case 1: pass\n    match y:\n        case 2: pass\n', 'match x:\n', 'match x:\n\n', 'match x:', 'match x: pass', 'match x: case 1: pass', 'match x:\n    case 1: case 2: pass\n',
    'match x:\n    case 1: match y:\n        case 2: pass\n', 'match x:\n    case 1: if a: pass\n', 'match:\n    case 1: pass\n', 'match :\n    case 1: pass\n', 'match *a:\n    case 1: pass\n',
    'match **a:\n    case 1: pass\n', 'match x y:\n    case 1: pass\n', 'match x = 1:\n    case 1: pass\n', 'match x: int:\n    case 1: pass\n', 'match yield:\n    case 1: pass\n',
    'match yield x:\n    case 1: pass\n', 'match pass:\n    case 1: pass\n', 'match if:\n    case 1: pass\n', 'match x for x in y:\n    case 1: pass\n',
    'match x:\n    case 1: pass\nelse:\n    pass\n', 'match x:\n    case 1: pass\ncase 2: pass\n', 'match x:\n        case 1: pass\n    case 2: pass\n', 'case 1: pass', 'case x:\n    pass\n',
    'case _: pass', 'if a: match x:\n    case 1: pass\n', 'if a: case 1: pass', 'else:\n    match x:\n        case 1: pass\n', 'match x\n    case 1: pass\n', 'match x', 'match x y', 'match 1',
    "match 'a'", 'match None', 'match lambda: 1', 'match not x', 'match x.y:', 'match x: int', 'match x, y: int', 'match -x: int', 'match x = 1', 'match x, y = 1', 'match x += 1', 'match (x):',
    'match (x):\n', 'match (x): int', 'match(x): int', 'match [x]:', 'match [x]:\n', 'match [x]:\n    pass\n', 'match (x):\n    pass\n', 'match = 1:\n    case 1: pass\n',
    'async match x:\n    case 1: pass\n', '@d\nmatch x:\n    case 1: pass\n', 'match x:\n    async case 1: pass\n', 'match x:\n    case 1: pass\n    @d\n    case 2: pass\n', 'lambda: match x',
    'x = match y:\n    case 1: pass\n', '(match x:\n    case 1: pass\n)', 'match x:\n    case C(a=1, a): pass\n', 'match x:\n    case C(a, b=): pass\n', "match x:\n    case {'a': 1, **_}: pass\n",
    'match x:\n    case {**_}: pass\n', "match x:\n    case {'a': *b}: pass\n", "match x:\n    case {'a': 1, **b, 'c': 2}: pass\n", 'match x:\n    case {**b,,}: pass\n',
    "match x:\n    case {'a' 'b': 1 1}: pass\n", 'match x:\n    case C(a, _=1): pass\n', 'match x:\n    case C(1, _=2): pass\n', 'match x:\n    case [_=1]: pass\n', 'match x:\n    case _.a: pass\n',
    'match x:\n    case _(): pass\n', 'match x:\n    case _.a(): pass\n', 'match x:\n    case {_: 1}: pass\n', 'match x:\n    case {a: 1}: pass\n', 'match x:\n    case a as _: pass\n',
    'match x:\n    case [*a] as _: pass\n', 'if a: with b: pass', 'if a: def f(): pass', 'if a: try: pass\nfinally: pass', 'if a: @d\ndef f(): pass', 'if a: class A: pass', 'if a: if b: pass',
    'if a: for x in y: pass', 'if a: while b: pass', 'if a: async def f(): pass', 'x = 1; with b: pass', 'x = 1; def f(): pass', 'x = 1; try: pass\nfinally: pass', 'x = 1; @d\ndef f(): pass',
    'while a: with b: pass', 'for x in y: def f(): pass', 'def f(): with b: pass', 'class A: def f(self): pass', 'with a: with b: pass', 'try: with b: pass\nfinally: pass', 'else: with b: pass',
    'x = def', 'x = try', 'x = with', 'x = @', 'f(def)', 'f(with)', 'f(try)', 'f(@)', 'f(k=with)', 'f(*def)', 'f(**try)', '[def]', '[x, with]', '(try)', '(x, @)', '{with: 1}', '{1: def}', '{x, try}',
    '{**with}', 'a[def]', 'a[1:with]', 'x if def else y', 'lambda: with', 'return def', 'del with', 'assert try', 'raise @', 'x: def', 'x: int = with', 'x += try', "f'{def}'", "f'{x:{with}}'",
    '[x for x in def]', '[x for x in y if with]', '@\ndef f(): pass', '@def\ndef f(): pass', 'x @ @ y', '@', 'def', 'try', 'with', 'x.def', 'x.with', 'import def', 'from a import with', 'global try',
    'for def in y: pass', 'with a as def: pass', 'try: pass\nexcept*: pass', 'try: pass\nexcept* E: pass\nexcept F: pass', 'try: pass\nexcept E: pass\nexcept* F: pass',
    'try: pass\nexcept* E: pass\nexcept: pass', 'try: pass\nexcept: pass\nexcept* E: pass', 'try: pass\nexcept* E, F: pass', 'try: pass\nexcept* E as e.f: pass', 'try: pass\nexcept* *E: pass',
    'try: pass\nexcept* x := E: pass', 'try: pass\nexcept** E: pass', 'try: pass\nexcept* E as: pass', 'try: pass\nexcept* E\n', 'try: pass\nexcept* yield: pass',
    'try: pass\nexcept* E: pass\nexcept* F: pass\nexcept G: pass', 'try: pass\nfinally: pass\nexcept* E: pass', 'try: pass\nelse: pass\nexcept* E: pass', 'except* E: pass',
]

# Accepted by the oracle, out of the ASCII-identifier subset: both lanes must answer Unsupported.
MATCH_UNSUPPORTED = [
    'match s:\n    case ﬁ: pass\n', 'match s:\n    case x.ﬁ: pass\n', 'match s:\n    case C(ﬁ=1): pass\n', 'match s:\n    case x as ﬁ: pass\n', 'match s:\n    case {**ﬁ}: pass\n',
    'match s:\n    case [*ﬁ]: pass\n', 'match ﬁ:\n    case 1: pass\n', 'match x:\n    case 1: ﬁ\n', 'try: pass\nexcept* E as ﬁ: pass', 'try: pass\nexcept* ﬁ: pass', 'match x:\n    case ﬁ: pass\n',
    'match x:\n    case a.ﬁ: pass\n', 'match x:\n    case ﬁ.a: pass\n', 'match x:\n    case ﬁ(): pass\n', 'match x:\n    case C(ﬁ=1): pass\n', 'match x:\n    case C(a=ﬁ): pass\n',
    'match x:\n    case 1 as ﬁ: pass\n', 'match x:\n    case [*ﬁ]: pass\n', 'match x:\n    case {**ﬁ}: pass\n', 'match x:\n    case {ﬁ.a: 1}: pass\n', "match x:\n    case {'a': ﬁ}: pass\n",
    'match x:\n    case 1 if ﬁ: pass\n', 'match x:\n    case 1 | ﬁ.b: pass\n', "match x:\n    case 'ﬁ': ﬁ\n",
]
